version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: auth_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client port
      - "8222:8222" # HTTP Management port

volumes:
  postgres_data:
  mongo_data:
